homeassistant:
  customize:

    # Locations
    sensor.suresh_location:
      friendly_name: Suresh
      icon: mdi:map-marker
    sensor.mallika_location:
      friendly_name: Mallika
      icon: mdi:map-marker
    sensor.srinika_location:
      friendly_name: Srinika
      icon: mdi:map-marker
    sensor.hasika_location:
      friendly_name: Hasika
      icon: mdi:map-marker

# Google Calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# Google Travel Times and Geo Code/Location
sensor:
    #  Address/Location Details
  - platform: google_geocode
    name: Suresh Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.suresh_suresh
    options: formatted_address
    display_zone: hide

  - platform: google_geocode
    name: Mallika Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.mallika_mallika
    options: formatted_address
    display_zone: hide

  - platform: google_geocode
    name: Srinika Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.srinika_srinika
    options: formatted_address
    display_zone: hide

  - platform: google_geocode
    name: Hasika Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.hasika_hasika
    options: formatted_address
    display_zone: hide