homeassistant:
  customize_domain:

    alarm_control_panel:
      homebridge_hidden: true

    binary_sensor:
      homebridge_hidden: true
      emulated_hue_hidden: true

    climate:
      homebridge_hidden: true
      emulated_hue_hidden: true

    cover:
      homebridge_hidden: true
      emulated_hue_hidden: true

    calendar:
      homebridge_hidden: true
      emulated_hue_hidden: true

    device_tracker:
      homebridge_hidden: true
      emulated_hue_hidden: true

    fan:
      homebridge_hidden: true
      emulated_hue_hidden: true

    input_boolean:
      homebridge_hidden: true
      emulated_hue_hidden: true

    light:
      homebridge_hidden: false
      emulated_hue_hidden: false

    lock:
      homebridge_hidden: true
      emulated_hue_hidden: true

    media_player:
      homebridge_hidden: true
      emulated_hue_hidden: true

    scene:
      homebridge_hidden: true
      emulated_hue_hidden: true

    remote:
      homebridge_hidden: true
      emulated_hue_hidden: true

    sensor:
      homebridge_hidden: true
      emulated_hue_hidden: true

    switch:
      homebridge_hidden: false
      emulated_hue_hidden: false